version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

networks:
  default:
    name: monorepo-network
