[services]
frontend = "client"
backend = "server"

[services.frontend.build]
builder = "DOCKERFILE"
dockerfilePath = "client/Dockerfile"

[services.frontend.deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.backend.build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"

[services.backend.deploy]
startCommand = "npm start"
healthcheckPath = "/api"  # Adjust this path as needed for your backend
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10